name: "[helm-locker] CI"

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name : Set up Go
        uses : actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Run CI
        run: BUILD_TARGET=helm-locker make ci
